#if __has_include("zen.tweaks.hpp")
#include "zen.tweaks.hpp"
#endif

#ifndef ZEN_CONFIG_WIDTH
#define ZEN_CONFIG_WIDTH 640
#endif

#ifndef ZEN_CONFIG_HEIGHT
#define ZEN_CONFIG_HEIGHT 480
#endif

#ifndef ZEN_CONFIG_SCALEMODE
#define ZEN_CONFIG_SCALEMODE SCALE_MODE::RESIZE
#endif

#ifndef ZEN_CONFIG_FULLSCREEN
#define ZEN_CONFIG_FULLSCREEN false
#endif

#ifndef ZEN_CONFIG_MIN_WIDTH
#define ZEN_CONFIG_MIN_WIDTH 0
#endif

#ifndef ZEN_CONFIG_MAX_WIDTH
#define ZEN_CONFIG_MAX_WIDTH 0
#endif

#ifndef ZEN_CONFIG_MIN_HEIGHT
#define ZEN_CONFIG_MIN_HEIGHT 0
#endif

#ifndef ZEN_CONFIG_MAX_HEIGHT
#define ZEN_CONFIG_MAX_HEIGHT 0
#endif

#ifndef ZEN_CONFIG_HIDDEN_DELTA
#define ZEN_CONFIG_HIDDEN_DELTA 100
#endif

#ifndef ZEN_CONFIG_TITLE
#define ZEN_CONFIG_TITLE "Zenith"
#endif

#ifndef ZEN_CONFIG_VERSION
#define ZEN_CONFIG_VERSION "1.0.0"
#endif

#ifndef ZEN_CONFIG_INPUT_KEYBOARD
#define ZEN_CONFIG_INPUT_KEYBOARD true
#endif

#ifndef ZEN_CONFIG_INPUT_MOUSE
#define ZEN_CONFIG_INPUT_MOUSE true
#endif

#ifndef ZEN_CONFIG_PIXELART
#define ZEN_CONFIG_PIXELART 0
#endif

#ifndef ZEN_CONFIG_CLEAR_BEFORE_RENDER
#define ZEN_CONFIG_CLEAR_BEFORE_RENDER 1
#endif

#ifndef ZEN_CONFIG_BACKGROUND_COLOR
#define ZEN_CONFIG_BACKGROUND_COLOR 0x000000
#endif

#ifndef ZEN_CONFIG_INPUT_SMOOTH_FACTOR
#define ZEN_CONFIG_INPUT_SMOOTH_FACTOR 0.
#endif

#ifndef ZEN_CONFIG_LOADER_PATH
#define ZEN_CONFIG_LOADER_PATH ""
#endif

#ifndef ZEN_CONFIG_LOADER_PREFIX
#define ZEN_CONFIG_LOADER_PREFIX ""
#endif

#ifndef ZEN_CONFIG_PNG_PREFIX
#define ZEN_CONFIG_PNG_PREFIX "iVBORw0KGgoAAAANSUhEUgAAACAAAAAg"
#endif

#ifndef ZEN_CONFIG_DEFAULT_IMAGE
#define ZEN_CONFIG_DEFAULT_IMAGE "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAABVJREFUeF7NwIEAAAAAgKD9qdeocAMAoAABm3DkcAAAAABJRU5ErkJggg=="
#endif

#ifndef ZEN_CONFIG_MISSING_IMAGE
#define ZEN_CONFIG_MISSING_IMAGE "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAJ9JREFUeNq01ssOwyAMRFG46v//Mt1ESmgh+DFmE2GPOBARKb2NVjo+17PXLD8a1+pl5+A+wSgFygymWYHBb0FtsKhJDdZlncG2IzJ4ayoMDv20wTmSMzClEgbWYNTAkQ0Z+OJ+A/eWnAaR9+oxCF4Os0H8htsMUp+pwcgBBiMNnAwF8GqIgL2hAzaGFFgZauDPKABmowZ4GL369/0rwACp2yA/ttmvsQAAAABJRU5ErkJggg=="
#endif

#ifndef ZEN_CONFIG_WHITE_IMAGE
#define ZEN_CONFIG_WHITE_IMAGE "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABdJREFUeNpi/P//PwMMMDEgAdwcgAADAJZuAwXJYZOzAAAAAElFTkSuQmCC"
#endif
